version: '3'
services:
    courses:
        image: winglim/hducourses
        environment:
            MONGODB_URL: mongodb://mongoadmin:secret@mongodb

    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: courses

    mongo_seed:
        image: winglim/hducoursesdb
        environment:
            USERNAME: mongoadmin
            PASSWORD: secret
        depends_on:
            - mongodb
