version: '3'
services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: courses

    mongo_seed:
        image: winglim/hducourses:db
        environment:
            USERNAME: mongoadmin
            PASSWORD: secret
        depends_on:
            - mongodb
